//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.20 at 12:38:29 PM MSK 
//


package xsd.image;

import lombok.Getter;
import lombok.Setter;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for ColorListItem complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ColorListItem"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ImageList" type="{}ImageListItem" maxOccurs="5000" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Color" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ColorListItem", propOrder = {
        "imageList"
})
public class ColorListItem {

    @XmlElement(name = "ImageList")
    protected List<ImageListItem> imageList;

    @Setter
    @Getter
    @XmlAttribute(name = "Color", required = true)
    protected String color;

    /**
     * Gets the value of the imageList property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the imageList property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImageList().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ImageListItem }
     *
     *
     */
    public List<ImageListItem> getImageList() {
        if (imageList == null) {
            imageList = new ArrayList<ImageListItem>();
        }
        return this.imageList;
    }

}
