//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.20 at 12:38:29 PM MSK 
//


package xsd.image;

import lombok.Getter;
import lombok.Setter;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for ImageListItem complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ImageListItem"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ImageFile"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="1"/&gt;
 *               &lt;maxLength value="1024"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="SourceFile"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="1"/&gt;
 *               &lt;maxLength value="1024"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="SizeList" type="{}SizeListItem" maxOccurs="5000" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="ImageWidth" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="ImageHeight" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImageListItem", propOrder = {
        "imageFile",
        "sourceFile",
        "sizeList"
})
public class ImageListItem {


    @Setter
    @Getter
    @XmlElement(name = "ImageFile", required = true)
    protected String imageFile;

    @Setter
    @Getter
    @XmlElement(name = "SourceFile", required = true)
    protected String sourceFile;

    @XmlElement(name = "SizeList")
    protected List<SizeListItem> sizeList;

    @Setter
    @Getter
    @XmlAttribute(name = "ImageWidth", required = true)
    protected int imageWidth;

    @Setter
    @Getter
    @XmlAttribute(name = "ImageHeight", required = true)
    protected int imageHeight;

    /**
     * Gets the value of the sizeList property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sizeList property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSizeList().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SizeListItem }
     *
     *
     */
    public List<SizeListItem> getSizeList() {
        if (sizeList == null) {
            sizeList = new ArrayList<SizeListItem>();
        }
        return this.sizeList;
    }
}
