//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.20 at 12:38:29 PM MSK 
//

package xsd.image;

import lombok.Getter;
import lombok.Setter;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;

/**
 * <p>Java class for ModelImageItem complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ModelImageItem"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ImageFileDefault"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="1"/&gt;
 *               &lt;maxLength value="1024"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="SourceFileDefault"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="1"/&gt;
 *               &lt;maxLength value="1024"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DefaultImageSizeList" type="{}SizeListItem" maxOccurs="5000" minOccurs="0"/&gt;
 *         &lt;element name="ColorList" type="{}ColorListItem" maxOccurs="5000" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="ModelNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ImageWidth" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="ImageHeight" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModelImageItem", propOrder = {
        "imageFileDefault",
        "sourceFileDefault",
        "defaultImageSizeList",
        "colorList"
})
@XmlRootElement(name = "ModelImage")
public class ModelImageItem {


    @Setter
    @Getter
    @XmlElement(name = "ImageFileDefault", required = true)
    protected String imageFileDefault;

    @Setter
    @Getter
    @XmlElement(name = "SourceFileDefault", required = true)
    protected String sourceFileDefault;

    @XmlElement(name = "DefaultImageSizeList")
    protected List<SizeListItem> defaultImageSizeList;

    @XmlElement(name = "ColorList")
    protected List<ColorListItem> colorList;

    @Setter
    @Getter
    @XmlAttribute(name = "ModelNumber", required = true)
    protected String modelNumber;

    @Setter
    @Getter
    @XmlAttribute(name = "ImageWidth", required = true)
    protected int imageWidth;

    @Setter
    @Getter
    @XmlAttribute(name = "ImageHeight", required = true)
    protected int imageHeight;

    /**
     * Gets the value of the defaultImageSizeList property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the defaultImageSizeList property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDefaultImageSizeList().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SizeListItem }
     *
     *
     */
    public List<SizeListItem> getDefaultImageSizeList() {
        if (defaultImageSizeList == null) {
            defaultImageSizeList = new ArrayList<SizeListItem>();
        }
        return this.defaultImageSizeList;
    }

    /**
     * Gets the value of the colorList property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the colorList property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getColorList().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ColorListItem }
     *
     *
     */
    public List<ColorListItem> getColorList() {
        if (colorList == null) {
            colorList = new ArrayList<ColorListItem>();
        }
        return this.colorList;
    }

    @Override
    public String toString() {
        String s = "";
        for (ColorListItem colorListItem : getColorList()) {
            if (colorListItem != null) {
                for (ImageListItem listItem : colorListItem.getImageList()) {
                    if (listItem != null) {
                        s += listItem.getImageFile() + " --- " + listItem.getSourceFile() + "\n";
                    }
                }
            }
        }

        return s;
    }
}
