//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.20 at 12:38:29 PM MSK 
//


package xsd.image;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xsd.image package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xsd.image
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ModelImageList }
     *
     */
    public ModelImageList createModelImageList() {
        return new ModelImageList();
    }

    /**
     * Create an instance of {@link ModelImageItem }
     *
     */
    public ModelImageItem createModelImageItem() {
        return new ModelImageItem();
    }

    /**
     * Create an instance of {@link ColorListItem }
     *
     */
    public ColorListItem createColorListItem() {
        return new ColorListItem();
    }

    /**
     * Create an instance of {@link ImageListItem }
     *
     */
    public ImageListItem createImageListItem() {
        return new ImageListItem();
    }

    /**
     * Create an instance of {@link SizeListItem }
     *
     */
    public SizeListItem createSizeListItem() {
        return new SizeListItem();
    }

}
