version: '3.8'

services:
  sql_global:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: Global
    environment:
      SA_PASSWORD: "YourPassword123!"  # Задай свой пароль
      ACCEPT_EULA: "Y"
    ports:
      - "1435:1433"
    volumes:
      - sql_data_global:/var/opt/mssql

  sql_gomel:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: Gomel
    environment:
      SA_PASSWORD: "YourPassword123!"  # Можно другой пароль
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data_gomel:/var/opt/mssql

  postgres_local:
    image: postgres:16
    container_name: Postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: march
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_local:/var/lib/postgresql/data

volumes:
  sql_data_global:
  sql_data_gomel:
  postgres_data_local:
