/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package dept.calculationprice;

import by.march8.ecs.framework.common.LogCrutch;

import javax.swing.*;


/**
 * @author user
 */
public class DialogRename extends javax.swing.JDialog {
    //private static final org.apache.log4j.Logger log = new Log().getLoger(PDB_new.class);
    private static final LogCrutch log = new LogCrutch();
    String active, name;
    int id;
    PricePDB db;
    CalculationPriceForm self;
    private javax.swing.JFormattedTextField etName;

    public DialogRename(String activeType, int id, CalculationPriceForm self, String name) {
        super(self, false);
        setLocationRelativeTo(self);
        this.active = activeType;
        this.id = id;
        this.self = self;
        this.name = name;
        initComponents();
        etName.setText(name);
        db = new PricePDB();
        db.conn();
        setVisible(true);
    }

    /**
     *
     */
    @SuppressWarnings("unused")
    public DialogRename() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        final JPanel jPanel1 = new JPanel();
        final JButton btnRename = new JButton();
        etName = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRename.setText("Переименовать");
        btnRename.addActionListener(DialogRename.this::btnRenameActionPerformed);
        jPanel1.add(btnRename, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 57, 253, -1));
        jPanel1.add(etName, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 12, 253, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * @param args the command line arguments
     */

    private void btnRenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRenameActionPerformed
        try {
            if (!etName.getText().isEmpty()) {
                if (active.equalsIgnoreCase("группа")) {
                    db.renameGroup(id, etName.getText());
                }
                if (active.equalsIgnoreCase("тип")) {
                    db.renameType(id, etName.getText());
                }
                if (active.equalsIgnoreCase("ассортимент")) {
                    db.renameAssortment(id + "", etName.getText());
                }

                self.updateJtreeCenEditor();
                this.dispose();
            }

        } catch (Exception e) {
            log.error("Ошибка при входе в систему: " + e);
            JOptionPane.showMessageDialog(null, "Ошибка получения данных", "Ошибка!!!", JOptionPane.ERROR_MESSAGE);
        }//GEN-LAST:event_btnRenameActionPerformed
    }

    /**
     *
     */
    @Override
    public void dispose() {
        super.dispose();
        db.disConn();
    }
    // End of variables declaration//GEN-END:variables
}
