/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package dept.calculationprice;

import javax.swing.*;

/**
 * @author user
 */
public class DialogDelete extends javax.swing.JDialog {
    //private static final org.apache.log4j.Logger log = new Log().getLoger(PDB_new.class);
    String active, name;
    int id;
    PricePDB db;
    CalculationPriceForm self;
    private javax.swing.JLabel tvMessage;

    public DialogDelete(String activeType, int id, CalculationPriceForm self, String name) {
        super(self, false);
        setLocationRelativeTo(self);
        this.active = activeType;
        this.id = id;
        this.self = self;
        this.name = name;
        initComponents();

        db = new PricePDB();
        db.conn();
        setVisible(true);

        if (active.equalsIgnoreCase("группа")) {
            tvMessage.setText("Удалить группу " + name + " ?");

        }
        if (active.equalsIgnoreCase("тип")) {
            tvMessage.setText("Удалить вид " + name + " ?");

        }
        if (active.equalsIgnoreCase("ассортимент")) {
            tvMessage.setText("Удалить ассортимент " + name + " ?");

        }

    }

    /**
     *
     */
    @SuppressWarnings("unused")
    public DialogDelete() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tvMessage = new javax.swing.JLabel();
        final JButton btnDelete = new JButton();
        final JButton btnCancel = new JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        tvMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnDelete.setText("Да");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnCancel.setText("Нет");
        btnCancel.addActionListener(this::btnCancelActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(tvMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(tvMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnDelete)
                                        .addComponent(btnCancel))
                                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        try {
            if (active.equalsIgnoreCase("группа")) {
                // db.deleteGroup(id);
                //  db.deleteTypeGroup(id);
                //  db.deleteCalcGroup(id);
                //  db.deleteAssortmentGroup(id);
            }
            if (active.equalsIgnoreCase("тип")) {
                //  db.deleteType(id);
                //  db.deleteCalcType(id);
                //  db.deleteAssortmentType(id);
            }
            if (active.equalsIgnoreCase("ассортимент")) {
                //System.out.println("удаление записи "+id);
                db.deleteAssortmentPrk(id);
                //   db.deletePtk(id + "");
                //  db.deleteCalcPtk(id + "");
            }

            self.updateJtreeCenEditor();
            this.dispose();
        } catch (Exception e) {
            //log.error("Ошибка при входе в систему: " + e);
            JOptionPane.showMessageDialog(null, "Ошибка получения данных", "Ошибка!!!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    // End of variables declaration//GEN-END:variables
    @Override
    public void dispose() {
        super.dispose();
        db.disConn();
    }
}
