/*
 * DescrModelForm.java
 *
 * Created on 04.06.2012, 15:57:40
 */
package dept.production.monitoring;

import common.ProgressBar;
import common.UtilFunctions;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author vova
 */
public class DescrModelForm extends javax.swing.JDialog {

    JDialog th;
    DefaultTableModel tModel;
    Object[][] rows;
    Object[] cols;
    String client;
    int kod_client = -5, fas, kod_brig;
    String sDate, eDate;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;


    public DescrModelForm(JDialog parent, boolean modal, int kod, int fas, int kod_brig, String brig, String sDate, String eDate) {
        super(parent, modal);
        th = this;
        this.sDate = sDate;
        this.eDate = eDate;

        this.kod_client = kod;
        this.fas = fas;
        this.kod_brig = kod_brig;

        cols = new Object[7];
        cols[0] = "Модель";
        cols[1] = "Артикул";
        cols[2] = "Наименование";
        cols[3] = "Рост";
        cols[4] = "Размер";
        cols[5] = "Цвет";
        cols[6] = "Кол-во";

        initComponents();
        initComponent();
        this.setTitle("Данные по участку");
        jLabel1.setText("Данные по участку: " + brig);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(180);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(60);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(60);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(120);

        setLocationRelativeTo(parent);
        setVisible(true);
    }

    private void initComponent() {
        final ProgressBar pb = new ProgressBar(th, false, "Сбор данных...");
        SwingWorker sw = new SwingWorker() {
            @Override
            protected Object doInBackground() throws Exception {
                MonitoringDB db = new MonitoringDB();
                rows = db.getDescrModelClient(kod_client, fas, kod_brig, UtilFunctions.convertDateStrToLong(sDate), UtilFunctions.convertDateStrToLong(eDate));
                return null;
            }

            @Override
            protected void done() {
                pb.dispose();
            }
        };
        sw.execute();
        pb.setVisible(true);

        tModel = new DefaultTableModel(rows, cols);
        jTable1.setModel(tModel);
        final TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tModel);
        jTable1.setRowSorter(sorter);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("jLabel1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String[]{
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(220, 220, 220)
                                                .addComponent(jLabel1)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // End of variables declaration//GEN-END:variables
}
