/*
 * ModelForm.java
 *
 * Created on 04.06.2012, 9:40:19
 */
package dept.production.monitoring;

import common.PanelWihtFone;
import common.ProgressBar;
import common.UtilFunctions;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author vova
 */
public class ModelForm extends javax.swing.JDialog {

    JDialog th;
    DefaultTableModel tModel;
    Object[][] rows;
    Object[] cols;
    String client;
    int kod_client = -5;
    String sDate, eDate;
    private PanelWihtFone mainPanel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;

    public ModelForm(JDialog parent, boolean modal, String client, int kod, String sDate, String eDate) {
        super(parent, modal);
        th = this;
        this.client = client;
        kod_client = kod;
        this.sDate = sDate;
        this.eDate = eDate;

        cols = new Object[6];
        cols[0] = "Модель";
        cols[1] = "Артикул";
        cols[2] = "Наименование";
        cols[3] = "Кол-во";
        cols[4] = "Код уч.";
        cols[5] = "Участок";

        initComponents();
        initComponent();
        this.setTitle("Процесс производства");
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(40);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(180);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(60);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(60);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(120);

        setLocationRelativeTo(parent);
        setVisible(true);
    }

    private void initComponent() {
        jLabel1.setText("Заказчик: " + client);
        final ProgressBar pb = new ProgressBar(th, false, "Сбор данных...");
        SwingWorker sw = new SwingWorker() {
            @Override
            protected Object doInBackground() throws Exception {
                MonitoringDB db = new MonitoringDB();
                rows = db.getModelClient(kod_client, UtilFunctions.convertDateStrToLong(sDate), UtilFunctions.convertDateStrToLong(eDate));
                return null;
            }

            @Override
            protected void done() {
                pb.dispose();
            }
        };
        sw.execute();
        pb.setVisible(true);

        tModel = new DefaultTableModel(rows, cols);
        //jTable1 = new JTable(tModel);
        jTable1.setModel(tModel);
        final TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tModel);
        jTable1.setRowSorter(sorter);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("jLabel1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String[]{
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Детали");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(280, 280, 280)
                                                .addComponent(jButton1))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(131, 131, 131)
                                                .addComponent(jLabel1)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jTable1.getSelectedRow() > -1) {
            int fas = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
            int kod_brig = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
            String brig = jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString();
            new DescrModelForm(th, false, kod_client, fas, kod_brig, brig, sDate, eDate);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    // End of variables declaration//GEN-END:variables
}
