/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dept.markerovka;

import dept.MyReportsModule;

import javax.swing.*;
import java.io.File;

/**
 *
 * @author Администратор
 * @date 27.03.2012
 */
public class AddLabelForm extends JDialog {

    JDialog thisForm = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton bAdd;
    private JButton bCancel;
    private JButton bPath;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JTextField tfName;
    private JTextField tfPath;
    /**
     * Creates new form AddLabelForm
     */
    public AddLabelForm(JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        thisForm = this;
        setLocationRelativeTo(parent);
        setResizable(false);
        setTitle("Добавление этикетки");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        tfPath = new javax.swing.JTextField();
        bPath = new javax.swing.JButton();
        bAdd = new javax.swing.JButton();
        bCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Имя");

        jLabel2.setText("Путь");

        tfPath.setEditable(false);

        bPath.setText("Выбрать");
        bPath.setMargin(new java.awt.Insets(2, 5, 2, 5));
        bPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPathActionPerformed(evt);
            }
        });

        bAdd.setText("Добавить");
        bAdd.setMargin(new java.awt.Insets(2, 5, 2, 5));
        bAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddActionPerformed(evt);
            }
        });

        bCancel.setText("Отмена");
        bCancel.setMargin(new java.awt.Insets(2, 5, 2, 5));
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(79, 79, 79)
                                                                .addComponent(bAdd)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(bCancel)
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(12, 12, 12)
                                                                .addComponent(tfPath))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(18, 18, 18)
                                                .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bPath)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(tfPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bPath))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bAdd)
                                        .addComponent(bCancel))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        dispose();
    }//GEN-LAST:event_bCancelActionPerformed

    private void bPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPathActionPerformed
        final JFileChooser fc = new JFileChooser(MyReportsModule.progPath + "/Labels/");
        fc.setFileFilter(new javax.swing.filechooser.FileFilter() {
            @Override
            public boolean accept(File f) {
                if (f != null)
                    if (f.isDirectory()) return true;

                return f.getName().toLowerCase().endsWith(".lbl");
            }

            @Override
            public String getDescription() {
                return "*.lbl";
            }
        });
        fc.setAcceptAllFileFilterUsed(false);

        if (fc.showDialog(thisForm, null) == JFileChooser.APPROVE_OPTION) {
            tfPath.setText(fc.getSelectedFile().getName());
        }
    }//GEN-LAST:event_bPathActionPerformed

    private void bAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddActionPerformed
        if (tfName.getText().trim().equals(""))
            JOptionPane.showMessageDialog(null, "Введите название этикетки", " Ошибка!!!", JOptionPane.ERROR_MESSAGE);
        else if (tfPath.getText().trim().equals(""))
            JOptionPane.showMessageDialog(null, "Выберите путь к этикетке", " Ошибка!!!", JOptionPane.ERROR_MESSAGE);
        else {
            MarkerovkaDB db = new MarkerovkaDB();
            db.addLabel(tfPath.getText().trim(), tfName.getText().trim());
            JOptionPane.showMessageDialog(null, "Этикетка добавлена", " ", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        }
    }//GEN-LAST:event_bAddActionPerformed
    // End of variables declaration//GEN-END:variables
}
