//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.05 at 12:10:49 PM MSK 
//


package by.march8.tasks.mnsati.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for descriptionType.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="descriptionType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="DEDUCTION_IN_FULL"/&gt;
 *     &lt;enumeration value="VAT_EXEMPTION"/&gt;
 *     &lt;enumeration value="OUTSIDE_RB"/&gt;
 *     &lt;enumeration value="IMPORT_VAT"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 *
 */
@XmlType(name = "descriptionType")
@XmlEnum
public enum DescriptionType {

    DEDUCTION_IN_FULL,
    VAT_EXEMPTION,
    OUTSIDE_RB,
    IMPORT_VAT;

    public static DescriptionType fromValue(String v) {
        return valueOf(v);
    }

    public String value() {
        return name();
    }

}
