//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.05 at 12:10:49 PM MSK 
//


package by.march8.tasks.mnsati.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for invoiceDocType.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="invoiceDocType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="ORIGINAL"/&gt;
 *     &lt;enumeration value="ADDITIONAL"/&gt;
 *     &lt;enumeration value="FIXED"/&gt;
 *     &lt;enumeration value="ADD_NO_REFERENCE"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 *
 */
@XmlType(name = "invoiceDocType")
@XmlEnum
public enum InvoiceDocType {

    ORIGINAL,
    ADDITIONAL,
    FIXED,
    ADD_NO_REFERENCE;

    public static InvoiceDocType fromValue(String v) {
        return valueOf(v);
    }

    public String value() {
        return name();
    }

}
