//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.05 at 12:10:49 PM MSK 
//


package by.march8.tasks.mnsati.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="general" type="{http://www.w3schools.com}general"/&gt;
 *         &lt;element name="provider" type="{http://www.w3schools.com}provider"/&gt;
 *         &lt;element name="recipient" type="{http://www.w3schools.com}recipient"/&gt;
 *         &lt;element name="senderReceiver" type="{http://www.w3schools.com}senderReceiver"/&gt;
 *         &lt;element name="deliveryCondition" type="{http://www.w3schools.com}deliveryCondition"/&gt;
 *         &lt;element name="roster" type="{http://www.w3schools.com}rosterList"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="sender" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "general",
        "provider",
        "recipient",
        "senderReceiver",
        "deliveryCondition",
        "roster"
})
@XmlRootElement(name = "issuance")
public class Issuance {

    @XmlElement(required = true)
    protected General general;
    @XmlElement(required = true)
    protected Provider provider;
    @XmlElement(required = true)
    protected Recipient recipient;
    @XmlElement(required = true)
    protected SenderReceiver senderReceiver;
    @XmlElement(required = true)
    protected DeliveryCondition deliveryCondition;
    @XmlElement(required = true)
    protected RosterList roster;
    @XmlAttribute(name = "sender", required = true)
    protected String sender;

    /**
     * Gets the value of the general property.
     *
     * @return
     *     possible object is
     *     {@link General }
     *
     */
    public General getGeneral() {
        return general;
    }

    /**
     * Sets the value of the general property.
     *
     * @param value
     *     allowed object is
     *     {@link General }
     *
     */
    public void setGeneral(General value) {
        this.general = value;
    }

    /**
     * Gets the value of the provider property.
     *
     * @return
     *     possible object is
     *     {@link Provider }
     *
     */
    public Provider getProvider() {
        return provider;
    }

    /**
     * Sets the value of the provider property.
     *
     * @param value
     *     allowed object is
     *     {@link Provider }
     *
     */
    public void setProvider(Provider value) {
        this.provider = value;
    }

    /**
     * Gets the value of the recipient property.
     *
     * @return
     *     possible object is
     *     {@link Recipient }
     *
     */
    public Recipient getRecipient() {
        return recipient;
    }

    /**
     * Sets the value of the recipient property.
     *
     * @param value
     *     allowed object is
     *     {@link Recipient }
     *
     */
    public void setRecipient(Recipient value) {
        this.recipient = value;
    }

    /**
     * Gets the value of the senderReceiver property.
     *
     * @return
     *     possible object is
     *     {@link SenderReceiver }
     *
     */
    public SenderReceiver getSenderReceiver() {
        return senderReceiver;
    }

    /**
     * Sets the value of the senderReceiver property.
     *
     * @param value
     *     allowed object is
     *     {@link SenderReceiver }
     *
     */
    public void setSenderReceiver(SenderReceiver value) {
        this.senderReceiver = value;
    }

    /**
     * Gets the value of the deliveryCondition property.
     *
     * @return
     *     possible object is
     *     {@link DeliveryCondition }
     *
     */
    public DeliveryCondition getDeliveryCondition() {
        return deliveryCondition;
    }

    /**
     * Sets the value of the deliveryCondition property.
     *
     * @param value
     *     allowed object is
     *     {@link DeliveryCondition }
     *
     */
    public void setDeliveryCondition(DeliveryCondition value) {
        this.deliveryCondition = value;
    }

    /**
     * Gets the value of the roster property.
     *
     * @return
     *     possible object is
     *     {@link RosterList }
     *
     */
    public RosterList getRoster() {
        return roster;
    }

    /**
     * Sets the value of the roster property.
     *
     * @param value
     *     allowed object is
     *     {@link RosterList }
     *
     */
    public void setRoster(RosterList value) {
        this.roster = value;
    }

    /**
     * Gets the value of the sender property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSender() {
        return sender;
    }

    /**
     * Sets the value of the sender property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSender(String value) {
        this.sender = value;
    }

}
