//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.05 at 12:10:49 PM MSK 
//


package by.march8.tasks.mnsati.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the by.march8.tasks.mnsati.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: by.march8.tasks.mnsati.model
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Issuance }
     *
     */
    public Issuance createIssuance() {
        return new Issuance();
    }

    /**
     * Create an instance of {@link General }
     *
     */
    public General createGeneral() {
        return new General();
    }

    /**
     * Create an instance of {@link Provider }
     *
     */
    public Provider createProvider() {
        return new Provider();
    }

    /**
     * Create an instance of {@link Recipient }
     *
     */
    public Recipient createRecipient() {
        return new Recipient();
    }

    /**
     * Create an instance of {@link SenderReceiver }
     *
     */
    public SenderReceiver createSenderReceiver() {
        return new SenderReceiver();
    }

    /**
     * Create an instance of {@link DeliveryCondition }
     *
     */
    public DeliveryCondition createDeliveryCondition() {
        return new DeliveryCondition();
    }

    /**
     * Create an instance of {@link RosterList }
     *
     */
    public RosterList createRosterList() {
        return new RosterList();
    }

    /**
     * Create an instance of {@link ConsignorList }
     *
     */
    public ConsignorList createConsignorList() {
        return new ConsignorList();
    }

    /**
     * Create an instance of {@link Consignor }
     *
     */
    public Consignor createConsignor() {
        return new Consignor();
    }

    /**
     * Create an instance of {@link ConsigneeList }
     *
     */
    public ConsigneeList createConsigneeList() {
        return new ConsigneeList();
    }

    /**
     * Create an instance of {@link Consignee }
     *
     */
    public Consignee createConsignee() {
        return new Consignee();
    }

    /**
     * Create an instance of {@link Contract }
     *
     */
    public Contract createContract() {
        return new Contract();
    }

    /**
     * Create an instance of {@link DocumentList }
     *
     */
    public DocumentList createDocumentList() {
        return new DocumentList();
    }

    /**
     * Create an instance of {@link Document }
     *
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link DocType }
     *
     */
    public DocType createDocType() {
        return new DocType();
    }

    /**
     * Create an instance of {@link RosterItem }
     *
     */
    public RosterItem createRosterItem() {
        return new RosterItem();
    }

    /**
     * Create an instance of {@link DescriptionList }
     *
     */
    public DescriptionList createDescriptionList() {
        return new DescriptionList();
    }

    /**
     * Create an instance of {@link Vat }
     *
     */
    public Vat createVat() {
        return new Vat();
    }

    /**
     * Create an instance of {@link ForInvoiceType }
     *
     */
    public ForInvoiceType createForInvoiceType() {
        return new ForInvoiceType();
    }

    /**
     * Create an instance of {@link TaxesType }
     *
     */
    public TaxesType createTaxesType() {
        return new TaxesType();
    }

}
