//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.05 at 12:10:49 PM MSK 
//


package by.march8.tasks.mnsati.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;


/**
 * Реквизиты поставщика
 *
 * <p>Java class for provider complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="provider"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="providerStatus" type="{http://www.w3schools.com}providerStatusType"/&gt;
 *         &lt;element name="dependentPerson" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="residentsOfOffshore" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="specialDealGoods" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="bigCompany" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="countryCode" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="unp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="branchCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="principal" type="{http://www.w3schools.com}forInvoiceType" minOccurs="0"/&gt;
 *         &lt;element name="vendor" type="{http://www.w3schools.com}forInvoiceType" minOccurs="0"/&gt;
 *         &lt;element name="declaration" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="dateRelease" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="dateActualExport" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="taxes" type="{http://www.w3schools.com}taxesType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "provider", propOrder = {
        "providerStatus",
        "dependentPerson",
        "residentsOfOffshore",
        "specialDealGoods",
        "bigCompany",
        "countryCode",
        "unp",
        "branchCode",
        "name",
        "address",
        "principal",
        "vendor",
        "declaration",
        "dateRelease",
        "dateActualExport",
        "taxes"
})
public class Provider {

    @XmlElement(required = true, defaultValue = "SELLER")
    @XmlSchemaType(name = "string")
    protected ProviderStatusType providerStatus;
    @XmlElement(defaultValue = "false")
    protected boolean dependentPerson;
    @XmlElement(defaultValue = "false")
    protected boolean residentsOfOffshore;
    @XmlElement(defaultValue = "false")
    protected boolean specialDealGoods;
    @XmlElement(defaultValue = "false")
    protected boolean bigCompany;
    protected BigInteger countryCode;
    protected String unp;
    protected String branchCode;
    protected String name;
    protected String address;
    protected ForInvoiceType principal;
    protected ForInvoiceType vendor;
    protected String declaration;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateRelease;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateActualExport;
    protected TaxesType taxes;

    /**
     * Gets the value of the providerStatus property.
     *
     * @return
     *     possible object is
     *     {@link ProviderStatusType }
     *
     */
    public ProviderStatusType getProviderStatus() {
        return providerStatus;
    }

    /**
     * Sets the value of the providerStatus property.
     *
     * @param value
     *     allowed object is
     *     {@link ProviderStatusType }
     *
     */
    public void setProviderStatus(ProviderStatusType value) {
        this.providerStatus = value;
    }

    /**
     * Gets the value of the dependentPerson property.
     *
     */
    public boolean isDependentPerson() {
        return dependentPerson;
    }

    /**
     * Sets the value of the dependentPerson property.
     *
     */
    public void setDependentPerson(boolean value) {
        this.dependentPerson = value;
    }

    /**
     * Gets the value of the residentsOfOffshore property.
     *
     */
    public boolean isResidentsOfOffshore() {
        return residentsOfOffshore;
    }

    /**
     * Sets the value of the residentsOfOffshore property.
     *
     */
    public void setResidentsOfOffshore(boolean value) {
        this.residentsOfOffshore = value;
    }

    /**
     * Gets the value of the specialDealGoods property.
     *
     */
    public boolean isSpecialDealGoods() {
        return specialDealGoods;
    }

    /**
     * Sets the value of the specialDealGoods property.
     *
     */
    public void setSpecialDealGoods(boolean value) {
        this.specialDealGoods = value;
    }

    /**
     * Gets the value of the bigCompany property.
     *
     */
    public boolean isBigCompany() {
        return bigCompany;
    }

    /**
     * Sets the value of the bigCompany property.
     *
     */
    public void setBigCompany(boolean value) {
        this.bigCompany = value;
    }

    /**
     * Gets the value of the countryCode property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getCountryCode() {
        return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setCountryCode(BigInteger value) {
        this.countryCode = value;
    }

    /**
     * Gets the value of the unp property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getUnp() {
        return unp;
    }

    /**
     * Sets the value of the unp property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setUnp(String value) {
        this.unp = value;
    }

    /**
     * Gets the value of the branchCode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getBranchCode() {
        return branchCode;
    }

    /**
     * Sets the value of the branchCode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBranchCode(String value) {
        this.branchCode = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the address property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAddress(String value) {
        this.address = value;
    }

    /**
     * Gets the value of the principal property.
     *
     * @return
     *     possible object is
     *     {@link ForInvoiceType }
     *
     */
    public ForInvoiceType getPrincipal() {
        return principal;
    }

    /**
     * Sets the value of the principal property.
     *
     * @param value
     *     allowed object is
     *     {@link ForInvoiceType }
     *
     */
    public void setPrincipal(ForInvoiceType value) {
        this.principal = value;
    }

    /**
     * Gets the value of the vendor property.
     *
     * @return
     *     possible object is
     *     {@link ForInvoiceType }
     *
     */
    public ForInvoiceType getVendor() {
        return vendor;
    }

    /**
     * Sets the value of the vendor property.
     *
     * @param value
     *     allowed object is
     *     {@link ForInvoiceType }
     *
     */
    public void setVendor(ForInvoiceType value) {
        this.vendor = value;
    }

    /**
     * Gets the value of the declaration property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDeclaration() {
        return declaration;
    }

    /**
     * Sets the value of the declaration property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDeclaration(String value) {
        this.declaration = value;
    }

    /**
     * Gets the value of the dateRelease property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDateRelease() {
        return dateRelease;
    }

    /**
     * Sets the value of the dateRelease property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDateRelease(XMLGregorianCalendar value) {
        this.dateRelease = value;
    }

    /**
     * Gets the value of the dateActualExport property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDateActualExport() {
        return dateActualExport;
    }

    /**
     * Sets the value of the dateActualExport property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDateActualExport(XMLGregorianCalendar value) {
        this.dateActualExport = value;
    }

    /**
     * Gets the value of the taxes property.
     *
     * @return
     *     possible object is
     *     {@link TaxesType }
     *
     */
    public TaxesType getTaxes() {
        return taxes;
    }

    /**
     * Sets the value of the taxes property.
     *
     * @param value
     *     allowed object is
     *     {@link TaxesType }
     *
     */
    public void setTaxes(TaxesType value) {
        this.taxes = value;
    }

}
