//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.05 at 12:10:49 PM MSK 
//


package by.march8.tasks.mnsati.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for recipientStatusType.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="recipientStatusType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="CUSTOMER"/&gt;
 *     &lt;enumeration value="CONSUMER"/&gt;
 *     &lt;enumeration value="CONSIGNOR"/&gt;
 *     &lt;enumeration value="COMMISSIONAIRE"/&gt;
 *     &lt;enumeration value="TAX_DEDUCTION_RECIPIENT"/&gt;
 *     &lt;enumeration value="FOREIGN_ORGANIZATION_BUYER"/&gt;
 *     &lt;enumeration value="TURNOVERS_ON_SALE_RECIPIENT"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 *
 */
@XmlType(name = "recipientStatusType")
@XmlEnum
public enum RecipientStatusType {

    CUSTOMER,
    CONSUMER,
    CONSIGNOR,
    COMMISSIONAIRE,
    TAX_DEDUCTION_RECIPIENT,
    FOREIGN_ORGANIZATION_BUYER,
    TURNOVERS_ON_SALE_RECIPIENT;

    public static RecipientStatusType fromValue(String v) {
        return valueOf(v);
    }

    public String value() {
        return name();
    }

}
