//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.05 at 12:10:49 PM MSK 
//


package by.march8.tasks.mnsati.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;


/**
 * Реквизиты получателя
 *
 * <p>Java class for recipient complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="recipient"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="recipientStatus" type="{http://www.w3schools.com}recipientStatusType"/&gt;
 *         &lt;element name="dependentPerson" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="residentsOfOffshore" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="specialDealGoods" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="bigCompany" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="countryCode" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="unp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="branchCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="declaration" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="taxes" type="{http://www.w3schools.com}taxesType" minOccurs="0"/&gt;
 *         &lt;element name="dateImport" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "recipient", propOrder = {
        "recipientStatus",
        "dependentPerson",
        "residentsOfOffshore",
        "specialDealGoods",
        "bigCompany",
        "countryCode",
        "unp",
        "branchCode",
        "name",
        "address",
        "declaration",
        "taxes",
        "dateImport"
})
public class Recipient {

    @XmlElement(required = true, defaultValue = "CUSTOMER")
    @XmlSchemaType(name = "string")
    protected RecipientStatusType recipientStatus;
    @XmlElement(defaultValue = "false")
    protected boolean dependentPerson;
    @XmlElement(defaultValue = "false")
    protected boolean residentsOfOffshore;
    @XmlElement(defaultValue = "false")
    protected boolean specialDealGoods;
    @XmlElement(defaultValue = "false")
    protected boolean bigCompany;
    protected BigInteger countryCode;
    protected String unp;
    protected String branchCode;
    protected String name;
    protected String address;
    protected String declaration;
    protected TaxesType taxes;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateImport;

    /**
     * Gets the value of the recipientStatus property.
     *
     * @return
     *     possible object is
     *     {@link RecipientStatusType }
     *
     */
    public RecipientStatusType getRecipientStatus() {
        return recipientStatus;
    }

    /**
     * Sets the value of the recipientStatus property.
     *
     * @param value
     *     allowed object is
     *     {@link RecipientStatusType }
     *
     */
    public void setRecipientStatus(RecipientStatusType value) {
        this.recipientStatus = value;
    }

    /**
     * Gets the value of the dependentPerson property.
     *
     */
    public boolean isDependentPerson() {
        return dependentPerson;
    }

    /**
     * Sets the value of the dependentPerson property.
     *
     */
    public void setDependentPerson(boolean value) {
        this.dependentPerson = value;
    }

    /**
     * Gets the value of the residentsOfOffshore property.
     *
     */
    public boolean isResidentsOfOffshore() {
        return residentsOfOffshore;
    }

    /**
     * Sets the value of the residentsOfOffshore property.
     *
     */
    public void setResidentsOfOffshore(boolean value) {
        this.residentsOfOffshore = value;
    }

    /**
     * Gets the value of the specialDealGoods property.
     *
     */
    public boolean isSpecialDealGoods() {
        return specialDealGoods;
    }

    /**
     * Sets the value of the specialDealGoods property.
     *
     */
    public void setSpecialDealGoods(boolean value) {
        this.specialDealGoods = value;
    }

    /**
     * Gets the value of the bigCompany property.
     *
     */
    public boolean isBigCompany() {
        return bigCompany;
    }

    /**
     * Sets the value of the bigCompany property.
     *
     */
    public void setBigCompany(boolean value) {
        this.bigCompany = value;
    }

    /**
     * Gets the value of the countryCode property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getCountryCode() {
        return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setCountryCode(BigInteger value) {
        this.countryCode = value;
    }

    /**
     * Gets the value of the unp property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getUnp() {
        return unp;
    }

    /**
     * Sets the value of the unp property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setUnp(String value) {
        this.unp = value;
    }

    /**
     * Gets the value of the branchCode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getBranchCode() {
        return branchCode;
    }

    /**
     * Sets the value of the branchCode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBranchCode(String value) {
        this.branchCode = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the address property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAddress(String value) {
        this.address = value;
    }

    /**
     * Gets the value of the declaration property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDeclaration() {
        return declaration;
    }

    /**
     * Sets the value of the declaration property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDeclaration(String value) {
        this.declaration = value;
    }

    /**
     * Gets the value of the taxes property.
     *
     * @return
     *     possible object is
     *     {@link TaxesType }
     *
     */
    public TaxesType getTaxes() {
        return taxes;
    }

    /**
     * Sets the value of the taxes property.
     *
     * @param value
     *     allowed object is
     *     {@link TaxesType }
     *
     */
    public void setTaxes(TaxesType value) {
        this.taxes = value;
    }

    /**
     * Gets the value of the dateImport property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDateImport() {
        return dateImport;
    }

    /**
     * Sets the value of the dateImport property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDateImport(XMLGregorianCalendar value) {
        this.dateImport = value;
    }

}
