//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.05 at 12:10:49 PM MSK 
//


package by.march8.tasks.mnsati.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;


/**
 * Данные по товарам (работам, услугам), имущественным правам
 *
 * <p>Java class for rosterList complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="rosterList"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="rosterItem" type="{http://www.w3schools.com}rosterItem" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="totalCostVat" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
 *       &lt;attribute name="totalExcise" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
 *       &lt;attribute name="totalVat" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
 *       &lt;attribute name="totalCost" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rosterList", propOrder = {
        "rosterItem"
})
public class RosterList {

    @XmlElement(required = true)
    protected List<RosterItem> rosterItem;
    @XmlAttribute(name = "totalCostVat", required = true)
    protected BigDecimal totalCostVat;
    @XmlAttribute(name = "totalExcise", required = true)
    protected BigDecimal totalExcise;
    @XmlAttribute(name = "totalVat", required = true)
    protected BigDecimal totalVat;
    @XmlAttribute(name = "totalCost", required = true)
    protected BigDecimal totalCost;

    /**
     * Gets the value of the rosterItem property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rosterItem property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRosterItem().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RosterItem }
     *
     *
     */
    public List<RosterItem> getRosterItem() {
        if (rosterItem == null) {
            rosterItem = new ArrayList<RosterItem>();
        }
        return this.rosterItem;
    }

    /**
     * Gets the value of the totalCostVat property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getTotalCostVat() {
        return totalCostVat;
    }

    /**
     * Sets the value of the totalCostVat property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setTotalCostVat(BigDecimal value) {
        this.totalCostVat = value;
    }

    /**
     * Gets the value of the totalExcise property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getTotalExcise() {
        return totalExcise;
    }

    /**
     * Sets the value of the totalExcise property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setTotalExcise(BigDecimal value) {
        this.totalExcise = value;
    }

    /**
     * Gets the value of the totalVat property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getTotalVat() {
        return totalVat;
    }

    /**
     * Sets the value of the totalVat property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setTotalVat(BigDecimal value) {
        this.totalVat = value;
    }

    /**
     * Gets the value of the totalCost property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getTotalCost() {
        return totalCost;
    }

    /**
     * Sets the value of the totalCost property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setTotalCost(BigDecimal value) {
        this.totalCost = value;
    }

}
