//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.05 at 12:10:49 PM MSK 
//


package by.march8.tasks.mnsati.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigDecimal;
import java.math.BigInteger;


/**
 * <p>Java class for rosterItem complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="rosterItem"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="number" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="code_oced" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;union&gt;
 *               &lt;simpleType&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                   &lt;length value="0"/&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/simpleType&gt;
 *               &lt;simpleType&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer"&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/simpleType&gt;
 *             &lt;/union&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="units" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="count" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="cost" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="summaExcise" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="vat" type="{http://www.w3schools.com}vat"/&gt;
 *         &lt;element name="costVat" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="descriptions" type="{http://www.w3schools.com}descriptionList" minOccurs="0"/&gt;
 *         &lt;element name="skipDeduction" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rosterItem", propOrder = {
        "number",
        "name",
        "code",
        "codeOced",
        "units",
        "count",
        "price",
        "cost",
        "summaExcise",
        "vat",
        "costVat",
        "descriptions",
        "skipDeduction"
})
public class RosterItem {

    @XmlElement(required = true)
    protected BigInteger number;
    @XmlElement(required = true)
    protected String name;
    protected String code;
    @XmlElement(name = "code_oced")
    protected String codeOced;
    protected BigInteger units;
    protected BigDecimal count;
    protected BigDecimal price;
    @XmlElement(required = true)
    protected BigDecimal cost;
    protected BigDecimal summaExcise;
    @XmlElement(required = true)
    protected Vat vat;
    @XmlElement(required = true)
    protected BigDecimal costVat;
    protected DescriptionList descriptions;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar skipDeduction;

    /**
     * Gets the value of the number property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setNumber(BigInteger value) {
        this.number = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the code property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the codeOced property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCodeOced() {
        return codeOced;
    }

    /**
     * Sets the value of the codeOced property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCodeOced(String value) {
        this.codeOced = value;
    }

    /**
     * Gets the value of the units property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getUnits() {
        return units;
    }

    /**
     * Sets the value of the units property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setUnits(BigInteger value) {
        this.units = value;
    }

    /**
     * Gets the value of the count property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setCount(BigDecimal value) {
        this.count = value;
    }

    /**
     * Gets the value of the price property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setPrice(BigDecimal value) {
        this.price = value;
    }

    /**
     * Gets the value of the cost property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getCost() {
        return cost;
    }

    /**
     * Sets the value of the cost property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setCost(BigDecimal value) {
        this.cost = value;
    }

    /**
     * Gets the value of the summaExcise property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getSummaExcise() {
        return summaExcise;
    }

    /**
     * Sets the value of the summaExcise property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setSummaExcise(BigDecimal value) {
        this.summaExcise = value;
    }

    /**
     * Gets the value of the vat property.
     *
     * @return
     *     possible object is
     *     {@link Vat }
     *
     */
    public Vat getVat() {
        return vat;
    }

    /**
     * Sets the value of the vat property.
     *
     * @param value
     *     allowed object is
     *     {@link Vat }
     *
     */
    public void setVat(Vat value) {
        this.vat = value;
    }

    /**
     * Gets the value of the costVat property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getCostVat() {
        return costVat;
    }

    /**
     * Sets the value of the costVat property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setCostVat(BigDecimal value) {
        this.costVat = value;
    }

    /**
     * Gets the value of the descriptions property.
     *
     * @return
     *     possible object is
     *     {@link DescriptionList }
     *
     */
    public DescriptionList getDescriptions() {
        return descriptions;
    }

    /**
     * Sets the value of the descriptions property.
     *
     * @param value
     *     allowed object is
     *     {@link DescriptionList }
     *
     */
    public void setDescriptions(DescriptionList value) {
        this.descriptions = value;
    }

    /**
     * Gets the value of the skipDeduction property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getSkipDeduction() {
        return skipDeduction;
    }

    /**
     * Sets the value of the skipDeduction property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setSkipDeduction(XMLGregorianCalendar value) {
        this.skipDeduction = value;
    }

}
