//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.05 at 12:10:49 PM MSK 
//


package by.march8.tasks.mnsati.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Реквизиты грузопоотправителя и грузополучателя
 *
 * <p>Java class for senderReceiver complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="senderReceiver"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="consignors" type="{http://www.w3schools.com}consignorList" minOccurs="0"/&gt;
 *         &lt;element name="consignees" type="{http://www.w3schools.com}consigneeList" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "senderReceiver", propOrder = {
        "consignors",
        "consignees"
})
public class SenderReceiver {

    protected ConsignorList consignors;
    protected ConsigneeList consignees;

    /**
     * Gets the value of the consignors property.
     *
     * @return
     *     possible object is
     *     {@link ConsignorList }
     *
     */
    public ConsignorList getConsignors() {
        return consignors;
    }

    /**
     * Sets the value of the consignors property.
     *
     * @param value
     *     allowed object is
     *     {@link ConsignorList }
     *
     */
    public void setConsignors(ConsignorList value) {
        this.consignors = value;
    }

    /**
     * Gets the value of the consignees property.
     *
     * @return
     *     possible object is
     *     {@link ConsigneeList }
     *
     */
    public ConsigneeList getConsignees() {
        return consignees;
    }

    /**
     * Sets the value of the consignees property.
     *
     * @param value
     *     allowed object is
     *     {@link ConsigneeList }
     *
     */
    public void setConsignees(ConsigneeList value) {
        this.consignees = value;
    }

}
