SELECT s_klient.KOD, s_klient.NAIM 
FROM (
	SELECT TOP 100 PERCENT CONTRACTOR  
		FROM MEGA_PLAIN_ANALYSIS 
		WHERE EXPORT>0
		GROUP BY CONTRACTOR
		ORDER BY CONTRACTOR
)AS CONTRACTOR
LEFT JOIN s_klient ON s_klient.KOD = CONTRACTOR.CONTRACTOR
ORDER BY s_klient.KOD