select CAT.NAME, C.ITEM_NAME, MIN(C.PRICE) AS MIN_PRICE, MAX(C.PRICE) AS MAX_PRICE  from ERP_REMAINS
LEFT JOIN VIEW_NSI_CLASSIFIER AS C ON C.ITEM_ID = ERP_REMAINS.SD_ID
LEFT JOIN NSI_CATEGORY AS CAT ON CAT.CODE = SUBSTRING(CONVERT(varchar(10), C.ARTICLE_CODE),1,3)
WHERE C.GRADE<2
GROUP BY SUBSTRING(CONVERT(varchar(10), C.ARTICLE_CODE),1,3),CAT.NAME, C.ITEM_NAME
ORDER BY SUBSTRING(CONVERT(varchar(10), C.ARTICLE_CODE),1,3), C.ITEM_NAME