UPDATE ERP_REMAINS
SET SD_ID = (
SELECT TOP 1 ITEM_CODE
FROM NSI_EANCODE
WHERE NSI_EANCODE.EANCODE = ERP_REMAINS.EANCOD
)

UPDATE ERP_REMAINS
SET CATEGORY = (
SELECT TOP 1 SUBSTRING(CONVERT(varchar(10), dbo.nsi_kld.sar),1,3) AS CATEGORY
FROM nsi_sd
INNER JOIN nsi_kld ON nsi_kld.kod = nsi_sd.kod
WHERE nsi_sd.kod1 = ERP_REMAINS.SD_ID
)

UPDATE ERP_REMAINS
SET NSI_COLOR = (
SELECT TOP 1 dbo.REFERENCE_COLOR.NAME
FROM NSI_EANCODE
INNER JOIN dbo.REFERENCE_COLOR ON dbo.REFERENCE_COLOR.ID = dbo.NSI_EANCODE.REF_COLOR_ID
WHERE NSI_EANCODE.EANCODE = ERP_REMAINS.EANCOD
)