select
NSI_WHOLESALE_CODE.CODE, nsi_pkd.nptk,
SUBSTRING(CONVERT(varchar(10), ARTICLE_NUMBER),1,2) AS ARTICLE,
sum(AMOUNT) AS AMOUNT_, sum(AMOUNT * PRICE) AS SUMMA



FROM VIEW_ERP_REMAINS

LEFT JOIN nsi_pkd on nsi_pkd.ptk = VIEW_ERP_REMAINS.PKD_CODE
LEFT JOIN NSI_WHOLESALE_CODE on NSI_WHOLESALE_CODE.ID = nsi_pkd.WHOLESALE_CODE

GROUP BY SUBSTRING(CONVERT(varchar(10), ARTICLE_NUMBER),1,2), NSI_WHOLESALE_CODE.CODE, nsi_pkd.nptk
ORDER BY SUBSTRING(CONVERT(varchar(10), ARTICLE_NUMBER),1,2),NSI_WHOLESALE_CODE.CODE, nsi_pkd.nptk
