select SUBSTRING(CONVERT(varchar(10), ARTICLE_NUMBER),1,2) AS ARTICLE,
CATEGORY,
sum(AMOUNT) AS AMOUNT_, sum(AMOUNT * PRICE) AS SUMMA, NSI_CATEGORY.NAME
FROM VIEW_ERP_REMAINS
LEFT JOIN NSI_CATEGORY ON NSI_CATEGORY.CODE = CATEGORY

GROUP BY SUBSTRING(CONVERT(varchar(10), ARTICLE_NUMBER),1,2), CATEGORY,NSI_CATEGORY.NAME
ORDER BY SUBSTRING(CONVERT(varchar(10), ARTICLE_NUMBER),1,2),CATEGORY
